# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/gestion_companies_aeriennes_backend/Dockerfile'
        tags: |
          $(tag)
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'service4iir'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'PublishProfile'
        PublishProfilePath: '$(System.DefaultWorkingDirectory)/**/*.pubxml'
        PublishProfilePassword: '123456'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'