version: '2.24.6'
services:
  mysql:
    container_name: mysql-cn
    image: mysql:8 
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - spring-net
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=gestion_ca
  backend:
    image: hossamchalabi/gestion_ca_backend
    container_name: backend-cn
    ports:
      - 8080:8080
    networks:
      - spring-net
    depends_on:
      - mysql       
    
volumes:
  db_data: {}

networks:
  spring-net:
    driver: bridge
